# Description
# ===========
# This workflow is triggered each time the Java CI workflow succeeds
# on master.
# It looks for a milestone that is completed and close it.
---
  name: Close Milestone
  
  on:
    push: 
      branches:
        - "*"
    
  
  jobs:
    close:
      name: Close completed milestone
      runs-on: ubuntu-latest
      steps:
        - name: Close a milestone if completed
          run: |
            milestones=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/milestones \
              | jq -r '. | map(select(.open_issues == 0 and .closed_issues > 0 and .state == "open"))')
            if [ "$milestones" != "[]" ]
            then
              milestone_number=$(echo "$milestones" | jq -r '.[0].number')
              curl -L \
                -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${GITHUB_REPOSITORY}/milestones/${milestone_number} \
                -d '{"state":"closed"}'
            fi