# Description
# ===========
# This workflow is triggered each time the Java CI workflow succeeds
# on master.
# It looks for a milestone that is completed and close it.
---
  name: Close Milestone
  
  on:
    pull_request: 
      branches:
        - main
    
  
  jobs:
    close:
      name: Close completed milestone
      runs-on: ubuntu-latest
      steps:
        - name: Close a milestone if completed
          run: |
            milestones=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/milestones \
              | jq -r '. | map(select(.open_issues == 0 and .closed_issues > 0 and .state == "open"))')
            if [ "$milestones" != "[]" ]
            then
              milestone_number=$(echo "$milestones" | jq -r '.[0].title')
              curl --request PATCH \
                --url https://api.github.com/repos/${GITHUB_REPOSITORY}/milestones/${milestone_number} \
                --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                --header 'Content-Type: application/json' \
                --data '{"state":"closed"}'
            fi